version: '2'

services:
  server:
    build: .
    ports:
      - "5000:5000"
    env_file: env.txt
    environment:
      - FEED_DIR=/var/lib/feed-store
      - MEDIA_DIR=/var/lib/media-store
    restart: always
    volumes:
      - /tmp/feed-store:/var/lib/feed-store
