version: '2'

services:
  server:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    env_file: env.txt
    environment:
      - FEED_DIR=/var/lib/feed-store
      - MEDIA_DIR=/var/lib/media-store
      - PROXY_DEPTH=1
    restart: always
    volumes:
      - /tmp/feed-store:/var/lib/feed-store
      - /tmp/media-store:/var/lib/media-store
